defaults:
  - _self_
  - task@_global_: reacher_hard
  - override hydra/launcher: submitit_local

im_w: 64
im_h: 64


# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
episode_len: 1000
max_num_encoder_videos: 5000
train_encoder_every_frames: 100
# eval
eval_every_frames: 10000
critic_target_tau: 0.01
num_eval_episodes: 5
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 100000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
save_video: true
save_train_video: true
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50
device: cuda
use_frame_state: true

virl_model:
  _target_: virl_model.ViRLModel
  lr: 1e-4
  hidden_dim: 128
  rho: 1

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: ???
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./rl_exp_local/${exp_group}/${exp_id}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
